version: '3.8'

services:
  mi_base_de_datos:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: microservicio_productos
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mi_app_web:
    build: .
    ports:
      - "8090:3000"
    depends_on:
      - mi_base_de_datos